name    'Ziaunys-tessera'
version '0.1.0'
source 'https://github.com/Ziaunys/puppet-tessera'
author 'Ziaunys'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'stankevich/python', '>=1.7.9'
dependency 'puppetlabs/vcsrepo', '>=1.1.0'
