name    'Ziaunys-tessera'
version '0.1.0'
source 'https://github.com/Ziaunys/puppet-tessera'
author 'Ziaunys'
license 'Apache License, Version 2.0'
summary 'Manages the deployment of the Tessera application'
description 'Tessera is a Graphite front-end'
project_page 'https://github.com/Ziaunys/puppet-tessera'

dependency 'stankevich/python', '>=1.7.9'
dependency 'puppetlabs/vcsrepo', '>=1.1.0'
